### ISSUE TITLE
EventHandler with sqlite: "cannot start a transaction within a transaction (1)"

### ISSUE THREAD

**Issue by scolin** [nikrou/eventHandler#32]
Hi,
trying to add an event when using an sqlite database ends up with the error message indicated in the subject.
Configuration:
- Dotclear: 2.10.2
- Database: sqlite 3.13
- EventHandler plugin: 2015.08.05
Steps to reproduce: install dotclear with an sqlite database, install the plugin, add an event.
I narrowed the error to the addEvent function, with this instruction:
$this->con->writeLock($this->table);

Some google-fu showed that this might be because sqlite does not like nested transactions (trying the same install and steps but with mysql does not throw an error). But I don't know enough about the plug-in if that's easily fixable or might require a refactor of the db interaction logic.

**Comment by nikrou** [comment]
Thanks for report. I confirm. Just need to fix it now !

**Comment by scolin** [comment]
Fix confirmed, thanks, that was fast !
