### ISSUE TITLE
Error trying to find coordinates with Gmaps & OSM

### ISSUE THREAD

**Issue by franck-tomek** [nikrou/eventHandler#34]
When trying to find the coordinates with Gmaps by clicking on the link to do so, here is the message I get : 
`Geocode was not successful for the following reason: ERROR`
No error but no more results with OSM.

DC 2.10.2 / Latest Eventhandler 2016.09.08

**Comment by nikrou** [comment]
I confirm. :-(

**Comment by franck-tomek** [comment]
Hi Nikrou, any chance to have a fix anytime soon? Thanks!
