### ISSUE TITLE
layout changes in DC V2.12 -> #entry-sidebar must be after #entry-wrapper

### ISSUE THREAD

**Issue by franck-tomek** [nikrou/eventHandler#38]
Starting with DC V2.12, the layout in the page for editing the event is now using Flexbox in CSS, and allow the sidebar to appear in second now in HTML, whereas it was in first before V2.12.
This issue is minor. :-)

**Comment by nikrou** [comment]
Fix in 5ed72733bb0465c398062ef18ff95a216c804a66
