### ISSUE TITLE
Add comment on event

### ISSUE THREAD

**Issue by PierreAmmeloot** [nikrou/eventHandler#39]
Do you have a method in order to add public comment on event page?

**Comment by nikrou** [comment]
I have to check if there's such method.
What is your idea exactly ?

**Comment by PierreAmmeloot** [comment]
Can we switch in french?

**Comment by PierreAmmeloot** [comment]
I wan't add a comment section after an event for my visitor. Same as a blog post on Dotclear. ;-)
