### ISSUE TITLE
Dernière version impossible à installer

### ISSUE THREAD

**Issue by franck-tomek** [nikrou/eventHandler#42]
"Erreur : Le fichier zip ne semble pas être un fichier de module Dotclear valide."
Même erreur que ce voit via le gestionnaire de plugins, ou en uploadant le fichier.

**Comment by franck-tomek** [comment]
Same problem with new version from today.

**Comment by nikrou** [comment]
I confirm. I need to understand what is the difference between theses archives.

**Comment by nikrou** [comment]
Fix with fdbd85f98528e267636baf9b34118fd25accd2f1
