### ISSUE TITLE
sort parameter in tpl:EventsOfPost not taken into account

### ISSUE THREAD

**Issue by franck-tomek** [nikrou/eventHandler#45]
In the tpl eventhandler-eventsofpost.html, whatever parameter is entered, the sorting is made by the date the event has been created. The parameter seems not to be taken into account.

**Comment by franck-tomek** [comment]
Example here: https://www.monakazu.net/post/2019/04/29/split-45-tours-foxeagle-/-mona-kazu-tournee
The sort parameter is set to "startdt".

**Comment by hubbubhum** [comment]
I have the same problem here : 
https://www.gonm.org/index.php?days/scheduled/startdt/desc

**Comment by franck-tomek** [comment]
Not fixed on latest version unfortunately.

**Comment by nikrou** [comment]
I confirm and I understand the problem. I need to find a way to fix it, now !
