### ISSUE TITLE
Fatal error / SQL

### ISSUE THREAD

**Issue by franck-tomek** [nikrou/eventHandler#46]
En faisant la mise à jour vers dotclear 2.21, un bug est apparu :

`You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'INNER JOIN dc_eventhandler EH ON EH.post_id = P.post_id WHERE P.blog_id = 'd...' at line 1 (1064)
Something went wrong while loading template file for your blog.`

et

`Fatal error: Uncaught Error: Call to a member function display() on null in /www/site/plugins/eventHandler/tpl/list_events.tpl:92 Stack trace: #0 /www/site/plugins/eventHandler/inc/index.events.php(403): include() #1 /www/site/plugins/eventHandler/index.php(80): include('/home/users5/a/...') #2 /www/dotclear/admin/plugin.php(43): include('/home/users5/a/...') #3 {main} thrown in /www/site/plugins/eventHandler/tpl/list_events.tpl on line 92`

**Comment by nikrou** [comment]
I can reproduce issue but do not understand why that comma comes from.

**Comment by franck-tomek** [comment]
Please check on Slack, there's been a talk about that this morning.
