### ISSUE TITLE
all "days" pages display "Dotclear" -> error

### ISSUE THREAD

**Issue by franck-tomek** [nikrou/eventHandler#53]
There seems to be a bug in the eventhandler-list.html template for "days" contexts. For instance, clicking on "All events" leads to a "Dotclear" error page.

It seems to happen only when using mustek tpl set.

**Comment by end4urip** [comment]
All events displays fine, when drilling down to display the day a template error happens. Also on the admin page the date columns have a flushed color the other columns are fine. 

Best to you
Kevin

**Comment by end4urip** [comment]
ie    https://nogov.us/days/all

**Comment by nikrou** [comment]
I confirm bug.

**Comment by end4urip** [comment]
Working much better.  Still have issue with listing of All
events. https://nogov.us/days/all/page/2   page two shows as Page 1.
Not all the events showing using 'All Events" but they are found using
the Calender Widget?
Map also shows on all events, no longer optional.

Best Regards,
Kevin

**Comment by nikrou** [comment]
I confirm. New release (2023-12-29) fixes pagination, map
