### ISSUE TITLE
fatal error on 2.27.1

### ISSUE THREAD

**Issue by franck-tomek** [nikrou/eventHandler#54]
Trying to get to the plugin admin page, here is the error:
`PHP Fatal error:  Uncaught TypeError: Dotclear\Helper\Html\Html::escapeJS(): Argument #1 ($str) must be of type ?string, bool given, called in /site/dc/src/Core/Backend/Page.php on line 1454 and defined in /site/dc/src/Helper/Html/Html.php:96
Stack trace:
#0 /site/dc/src/Core/Backend/Page.php(1454): Dotclear\Helper\Html\Html::escapeJS()
#1 /site/site/plugins/eventHandler/tpl/list_events.tpl(9): Dotclear\Core\Backend\Page::jsVar()
#2 /site/site/plugins/eventHandler/inc/index.events.php(432): include('/site/...')
#3 /site/site/plugins/eventHandler/index.php(79): include('/site/...')
#4 /site/dc/src/Process/Backend/Plugin.php(70): include('/site/...')
#5 /site/dc/src/App.php(99): Dotclear\Process\Backend\Plugin::render()
#6 /site/dc/src/App.php(75): Dotclear\App::process()
#7 /site/dc/admin/index.php(16): Dotclear\App::bootstrap()
#8 {main}
  thrown in /site/dc/src/Helper/Html/Html.php on line 96`

And The plugin is not functional on 2.27.1, no event displayed on frontend.

**Comment by nikrou** [comment]
Fix with release 2023.10.07
